name: deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy Trigger
        run: |
          curl -X POST http://ec2-3-37-14-140.ap-northeast-2.compute.amazonaws.com:20001/job/animory-fe-deploy/build \
          --user admin:${{ secrets.JENKINS_DEPLOY_KEY }}